### ISSUE TITLE
Wanted: WithChildren(OsmGeo, IOsmGeoSource)

### ISSUE THREAD

**Issue by blackboxlogic** [OsmSharp/core#102]
A few times now, I have an element (like a way) which I want to put in an OSM file, but I must also include the child elements (like the way's nodes) or the file won't be complete and render-able. I've been using a recursive function called WithChildren(), but I'm copying it between projects and it seems like it might belong in Core.
```c#
IEnumerable<OsmGeo> WithChildren(OsmGeo parent, IOsmGeoSource possibleChilden)
```
Does a function like this already exist? If not, would you consider a pull request with this function and where would you want it to live?

**Comment by xivk** [comment]
I think this is the equivalent:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/Complete/Extensions.cs#L38

**Comment by xivk** [comment]
But none that has an IEnumerable<OsmGeo> as result.

**Comment by blackboxlogic** [comment]
Subtle difference, I'm not looking for a single complete way, I'm looking for a way and its 6  nodes, so I want 7 non-complete elements, which is the form needed to write an osm file.

**Comment by blackboxlogic** [comment]
Maybe ICompleteElement could have .AsComponents()

**Comment by xivk** [comment]
The 'completeway' has those 6 nodes, but yes, it would probably be a good idea to add this. There is also this one:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/Streams/Complete/OsmToCompleteStreamSource.cs

When you filter a stream, leaving all nodes in and the one way, it should return the way and the nodes.

**Comment by xivk** [comment]
This sample does exactly that: https://github.com/OsmSharp/core/tree/develop/samples/Sample.CompleteStream

**Comment by blackboxlogic** [comment]
Maybe code will communicate more clearly than English. I offer this PR without any urgency, take a look when you have time.

**Comment by blackboxlogic** [comment]
> This sample does exactly that: https://github.com/OsmSharp/core/tree/develop/samples/Sample.CompleteStream

That sample creates complete elements from simple elements, I'm looking for the opposite, given a complete element, get the simple elements that compose it.
