### ISSUE TITLE
DefaultFeatureInterpreter.InterpretMultipolygonRelation method is not taking into account members without role

### ISSUE THREAD

**Issue by Alexey-Stolyarov** [OsmSharp/core#11]
This fact disallows interpret a number of administrative boundaries in most of countries. I think, members without roles should be considered as "outer" (from here: http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Members)

**Comment by xivk** [comment]
What can you suggest to fix this? The default feature interpreter is a very simple example of what's possible but it may be a good idea to get it to a point where it is as good as possible for current OSM data. 

The perfect implementation however would allow for a configurable option without the need to rebuild the code.

**Comment by APLANA-Alexey-Stolyarov** [comment]
As a simple fix I suggest interpret relation as outer if it's not marked as inner. I don't think that this is doable create configurable code for any case of OSM input data. Maybe this is good idea to create DefaultFeatureInterpreter as a pattern, that uses well realized converting methods (like, relations to multipolygon, way to line, node to POI, etc.).  Any could extend such interpreter as he need.

**Comment by xivk** [comment]
Can you provide me with an example of a relation that should be interpreted like this? Are you sure there isn't an error on the tagging?

**Comment by APLANA-Alexey-Stolyarov** [comment]
Yes. I'll try find some cases for this issue.

**Comment by APLANA-Alexey-Stolyarov** [comment]
Look at this relation: http://www.openstreetmap.org/relation/114071 and see way #33204842 into it. This relation contains inner, outer, and not specified roles (which should be interpreted as outer, regarding OSM's wiki).

**Comment by xivk** [comment]
This is now part of #32
