### ISSUE TITLE
Is OsmSharp secure against XML external entity injection (XXE) attacks and other XML parsing attacks ? 

### ISSUE THREAD

**Issue by redshmi** [OsmSharp/core#119]
Is OsmSharp secure against XML external entity injection (XXE) attacks and other XML parsing attacks ? 
For Reference : https://gist.github.com/mgeeky/4f726d3b374f0a34267d4f19c9004870

**Comment by xivk** [comment]
I'm not sure so I will say no, only parse data from trusted sources. 

Also not planned at the moment to take this into account.
