### ISSUE TITLE
Add default comparers

### ISSUE THREAD

**Issue by xivk** [OsmSharp/core#120]
Add default comparers for by implementing [IComparable<T>](https://docs.microsoft.com/en-us/dotnet/api/system.icomparable-1?view=net-5.0):

- [ ] OsmGeo: Compares using type, id and version.
- [ ] OsmGeoKey: Compare using type and id.
- [ ] OsmGeoKeyAndVersion: Compare using type, id and version.

Code to be called when implementing the interface:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/Extensions.cs#L46

**Comment by pietervdvn** [comment]
1) I've moved the code over to the OSMGeo-object, the Extension method is kept for backwards compatibility but simply invokes the native compare method. Should I change current usages of the extension method to the new, native method?

2) Was already implemented

3) I've interpreted this as `OsmGeoVersionKey` (assuming that this class is meant with `OsmGeoKeyAndVersion`)
