### ISSUE TITLE
Running into System.IO.EndOfStreamException

### ISSUE THREAD

**Issue by bryanschoot** [OsmSharp/core#125]
Pretty new to this but I'am running into an issues,

So when I get the osm/pbf data of the Netherlands and try to extract all  'Way's with the  'highway' as Tag (key) it throws me EndOfStreamException.

See code below:

```
using var fileStream = File.OpenRead(file); // file <- "netherlands-latest.osm.pbf"

var source = new PBFOsmStreamSource(fileStream);
var filtered = from osmGeo in source 
                      where osmGeo.Type == OsmGeoType.Way && osmGeo.Tags.ContainsKey("highway") 
                      select osmGeo;
var completeSource = source.ToComplete();

foreach (var osmGeo in completeSource )
{
        Console.WriteLine(osmGeo.ToString());
}
```

Is my the pbf file to big am I doing something wrong? I have no clue :(

Also I dont know if this belongs here but I am posting it either way

**Comment by bryanschoot** [comment]
It does not happen when using smaller pbf files for ex. provinces

**Comment by xivk** [comment]
Are you sure the PBF is consistent, downloaded completely?

**Comment by bryanschoot** [comment]
It is downloaded from https://download.geofabrik.de/europe/netherlands-latest.osm.pbf
Stored on local pc

`
 public static void Download(string url, string filename)
        {
            if (File.Exists(filename))
            {
                return;
            }

            var client = new WebClient();
            client.DownloadFile(url, filename);
        }
`

And then used

**Comment by xivk** [comment]
Could it have been partially downloaded? When stopping the application running while downloading will leave the file in place but it will be only partially downloaded.

**Comment by bryanschoot** [comment]
Well that seems to be the problem... Sorry for wasting your time! But for what it's worth, thanks, I didn't think of it :)
