### ISSUE TITLE
OSM pbf read performance

### ISSUE THREAD

**Issue by Doidel** [OsmSharp/core#137]
I know there have been discussions on future improvements, yet I'm still wondering why this doesn't improve performance:

My initial naive code:
```csharp
using (var stream = File.OpenRead("switzerland.pbf"))
{
    routerDb.LoadOsmData(stream);
}
```
This takes 5 minutes.

So I thought I can make this faster by cropping a submap and using some settings:
```csharp
using (var stream = File.OpenRead("switzerland.pbf"))
{
    var source = new PBFOsmStreamSource(stream);

    var filtered = source.FilterSpatial(polygon);

    routerDb.LoadOsmData(filtered, new LoadSettings()
    {
        AllCore = true,
        KeepNodeIds = false,
        KeepWayIds = false
    }, Vehicle.Bus);

    routerDb.LoadOsmData(stream);
}
```
This takes 6 minutes...

Do you have any tips or tricks on how to improve performance?
I only use the map for a distance matrix calculation, that's all.

Thanks and best regards,
Roman

**Comment by DavidKarlas** [comment]
I think what you will want to do is use Itinero database caching capability, see below example code:
```
RouterDb routerDb;
string routerDbCache = "switzerlandRoutingCache.db";
string pbfPath = "switzerland.pbf";
if (File.Exists(routerDbCache))
{
    using var fs = new FileStream(routerDbCache, FileMode.Open);
    routerDb = RouterDb.Deserialize(fs);
}
else
{
    using var fs = new FileStream(pbfPath, FileMode.Open);
    var osmSource = new PBFOsmStreamSource(fs);
    routerDb = new RouterDb();
    using var stream = new FileStream("pedestrian.lua", FileMode.Open);
    routerDb.LoadOsmData(filtered, new LoadSettings()
    {
        AllCore = true,
        KeepNodeIds = false,
        KeepWayIds = false
    }, Vehicle.Bus);
    using var cacheWriter = new FileStream(routerDbCache, FileMode.Create);
    routerDb.Serialize(cacheWriter);
}
var router = new Router(routerDb);
```

**Comment by Doidel** [comment]
Thanks for the suggestion, and yes I'm aware of that and it's an awesome cache which makes subsequent loads substantially faster.
I want to read in the latest "switzerland.pbf" daily though, that's why I was wondering.

**Comment by DavidKarlas** [comment]
I'm not sure what kind of app you are creating, but maybe could have some kind of service or cron job that daily creates conversion on some server and then everything else just downloads "switzerlandRoutingCache.db" from that server.
Would probably save bandwidth and processing...

**Comment by DavidKarlas** [comment]
Going back to your original question... how big is polygon? is it 1% of Switzerland or is it more like 50%?

**Comment by Doidel** [comment]
Yep, the preprocessing would definitely be an option, and not a bad one either. That would work fine, I just tested initially whether it's actually even necessary.
Maybe ~10%.
