### ISSUE TITLE
geocoding

### ISSUE THREAD

**Issue by merlitti** [OsmSharp/core#16]
hi everybody,
great work, this library seems fantastic.
I've only a question: how can I manage a geocoding feature? My need is to resolve a coordinate (Lat Lon) with the corresponding street in a fast manner.
Is it possible?
Thanks in advance!

Nicola

**Comment by xivk** [comment]
Geocoding is something completely different. You could use OsmSharp to load OSM data and process it to build a geocoder but this is very very complex. 

I suggesting using one of the existing solutions or just using an online service.

**Comment by merlitti** [comment]
Thanks xivk for the fast reply! What do you mean with "existing solutions". Can you give me an hint?

**Comment by xivk** [comment]
There is an overview of some services here:

https://wiki.openstreetmap.org/wiki/Search_engines

And then there is this:

https://github.com/itinero/Geocoding.net
