### ISSUE TITLE
Missing etensionType in gpx class

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#21]
Since I'm using OSM Sharp in my project and I have the gpx xsd I wanted to remove it from my code assuming I can use ```OsmSharp.IO.Xml.Gpx.v1_1```.
Unfortunately I couldn't find ```extensionsType``` in the above namespace.
Am I missing something?
xsd can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Gpx/GpxTypes.xsd
cs generated file can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Gpx/GpxTypes.cs

**Comment by xivk** [comment]
I'm not really up-to-date on the GPX-format. I also removed this functionality in the latest release:

https://github.com/OsmSharp/core/tree/develop/src/OsmSharp/IO

The new philosophy of OsmSharp is: do only OSM-related stuff. Exporting/importing geometries to/from GPX is not part of this. I filed an issue for you in the NTS library related to GPX.

**Comment by HarelM** [comment]
I think this is covered in this issue.
https://github.com/NetTopologySuite/NetTopologySuite/issues/147
