### ISSUE TITLE
Element latitude/longitude are private

### ISSUE THREAD

**Issue by louisap2** [OsmSharp/core#24]
Hi,

Going through the elements in my source file like this:

```
using (var fileStream = new FileInfo("C://Temp//OpenStreetMap//berlin_germany.osm.pbf").OpenRead())
{
	int counter = 0;

	var source = new PBFOsmStreamSource(fileStream);

	foreach (var element in source)
	{
		// element.Latitude; // private
		// element.Longitude; // private

		textBox1.Text += element.ToString() + Environment.NewLine;

		counter++;
		if (counter >= 10)
			break;
	}
}
```

I would love to also get the latitude/longitude for each element, but for some reason these two variables are private.

Can you share a secret trick to access latitude/longitude for each element in a stream?

Thanks!

**Comment by xivk** [comment]
Lat/lon is not private, you need to cast the 'element' object of type OsmGeo to a Node/Way or Relation object.

**Comment by louisap2** [comment]
That fixed the problem. Thanks.

**Comment by xivk** [comment]
No problem, just add another issue if you have any more issues... 👍
