### ISSUE TITLE
[Question] OsmSharp based Tile server implementation

### ISSUE THREAD

**Issue by pherbel** [OsmSharp/core#25]
Hi,
I would like to test a .Net base tile service.
Coluld you help me please with the right direction? Are there any project/repository with sample or working solution?

**Comment by xivk** [comment]
I made the tile server repo private because it's not even close to ready for any production scenario and development on has stopped. I could give you access, I was getting too many questions about it and I don't support it anymore so you'll be on your own... :-)

https://github.com/itinero/osmsharp-tile-server

**Comment by pherbel** [comment]
Ooh I see. Then please give me access. I check it out

**Comment by xivk** [comment]
Done, this uses an older version of OsmSharp when there was still rendering code in there and loads all data in memory.

For a longer term solution for rendering tiles in .NET it's best to look at https://github.com/pauldendulk/Mapsui I recommend this project as a replacement for the old OsmSharp UI project.

**Comment by pauldendulk** [comment]
Mapsui now uses SkiaSharp for rendering. This should also behave properly on the server. The Mapsui Skia renderer can be found here: https://github.com/pauldendulk/Mapsui/tree/master/Mapsui.Rendering.Skia-PCL

This renderer expects Mapsui geometries. I think the best approach is to use parts of this code and replace the geometries for whatever you use as osmsharp geometries.

**Comment by pherbel** [comment]
Thanks the help guys. And sorry If I came up with a stupid question, but I'm very new on this map rendering/processing area. So any help very welcome. :-)

Actually I would like to experiment a .Net based tile service which can serve vector tiles.

I imagine this service with map database which processed and loaded from osm dump periodically.
Tile service is connecting to this database and can query and render the vector tiles data for the HTML frontend. The HTML frontend would be a OpenLayes page which can handle the tiles, layes, etc.

**Comment by pherbel** [comment]
@xivk Could you help me to find the code which create a Tile from OSM stream?

**Comment by pherbel** [comment]
@pauldendulk Thanks. I checked the code what you refer, but it seems to me it is image rendering

Can I use Mapsui to render Vector Tile object and serialize it to GeoJson or Mapbox Vector Tile format?

**Comment by pauldendulk** [comment]
My remark was before you mentioned you were interested in vector tiles. The server side skia rendering would indeed only be useful for images. 

I would also like to implement vector tile rendering in Mapsui, btw.

**Comment by xivk** [comment]
@pherbel I will be working on this in https://github.com/itinero/routing to serve vector tiles for the road network that's loaded but for generic OSM data it's a difficult problem.

I would say use NTS and OsmSharp together to convert OSM data to geometries, there is a sample for that, and then use NTS to cut into tiles.

Sounds easy right? It's not... sorry... :-) We don't have a good solution but there are some non-.NET tools out there like tilemaker:

https://github.com/systemed/tilemaker

**Comment by james-gould** [comment]
@xivk Cold you add me to the private repo for the tile server as well please? It's something I'm interested in implementing, would be interesting to see how much has been done and where I can help out. Cheers!

**Comment by xivk** [comment]
@james-gould Made the repo public again,:

https://github.com/itinero/osmsharp-tile-server
