### ISSUE TITLE
ToSimple method is missing?

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#28]
Hi, I stated a migration to .Net Core and I'm using the alpha version, but there is a method that I'm using in order to update the OSM database called ```ToSimple()``` which is no longer supported in latest release.
Is there a change to bring it back?
Use case scenario:
1. Get complete way from OSM
2. test stuff against this full way
3. add a point to that way
4. update way in OSM.

By the way, great change in OSM API and regular POCOs!
Thanks, Keep up the good work!

**Comment by xivk** [comment]
Ok, there are conversion methods already, I'll have a look.

Also, there is no need to use the alpha, the latest stable also has netcore support.

**Comment by xivk** [comment]
Yep, you are right, they should be here but they aren't:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/Complete/Extensions.cs

Will have a look later or feel free to submit a pull-request. Will probably do this sometime next week.

**Comment by HarelM** [comment]
I can wait, the migration process is talking longer than I anticipated.
BTW, why use extension methods when the code "belongs" to you? Why not just add it to the class itself?

**Comment by HarelM** [comment]
Any updates on this?

**Comment by HarelM** [comment]
Thanks!!! Kudos on all your work (here and in NTS).
