### ISSUE TITLE
Problem with deserialization of OSM object

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#29]
Not sure if this is related to the fact that I'm using the alpha version or not but after the Osm class change the following test fails:

```cs
    [TestClass]
    public class OsmSerialization
    {
        [TestMethod]
        public void TestDeserializationOfUserDetailsResponse()
        {
            var resonseString = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<osm version=\"0.6\" generator=\"OpenStreetMap server\">\n  <user id=\"111\" display_name=\"Test\" account_created=\"2013-03-09T17:55:56Z\">\n    <description></description>\n    <contributor-terms agreed=\"true\" pd=\"false\"/>\n    <img href=\"http://www.gravatar.com/avatar/not-a-real-one.jpg?s=256&amp;d=http%3A%2F%2Fwww.openstreetmap.org%2Fassets%2Fusers%2Fimages%2Flarge-afe7442b856c223cca92b1a16d96a3266ec0c86cac8031269e90ef93562adb72.png\"/>\n    <roles>\n    </roles>\n    <changesets count=\"226\"/>\n    <traces count=\"27\"/>\n    <blocks>\n      <received count=\"0\" active=\"0\"/>\n    </blocks>\n    <home lat=\"30.0\" lon=\"30.0\" zoom=\"3\"/>\n    <languages>\n      <lang>he</lang>\n      <lang>en-US</lang>\n      <lang>en</lang>\n    </languages>\n    <messages>\n      <received count=\"14\" unread=\"0\"/>\n      <sent count=\"9\"/>\n    </messages>\n  </user>\n</osm>\n";
            var stream = new MemoryStream(UTF8Encoding.UTF8.GetBytes(resonseString));
            var serializer = new XmlSerializer(typeof(Osm));
            var osm = serializer.Deserialize(stream) as Osm;
            Assert.IsNotNull(osm.User);
        }
    }
```

This is a (modified for privacy reasons) string of the response I'm getting from the Osm Api server.

**Comment by xivk** [comment]
What's the exception/problem you are having exactly?

**Comment by HarelM** [comment]
The above test fails, user property is returned as null.

**Comment by HarelM** [comment]
I'm not sure this is the best solution though, I think adding relevant xml attributes on the classes' properties might make the code more maintainable.

**Comment by xivk** [comment]
I'll review as soon as I have the time. I also implemented something similar in the past so it's possible I'll modify the code a bit before accepting.

I didn't really see the usecase for OsmSharp to work directly with the OSM-API, I did in the past and it makes sense to include this functionality.

Thanks for the effort in any case.

**Comment by HarelM** [comment]
I think the OSM API inside this library is a great match. I currently have a locally compiled version I'm using, let me know when you update the NuGet package.

**Comment by HarelM** [comment]
Any updates on this? I want to bring my build server back up and I don't want to write code to install local packages...

**Comment by HarelM** [comment]
@xivk any updates on this? my PR open for a while now... Also I would like to remove the locally created NuGet packages from my project...

**Comment by HarelM** [comment]
This was closed back in may.
