### ISSUE TITLE
The process cannot access the filre because it is being used by another process.

### ISSUE THREAD

**Issue by hmanning** [OsmSharp/core#35]
Target.Close(); does not close the stream to the file, instead it continues to keep open in the application. 

https://puu.sh/xbOFe/51c49d915a.png

**Comment by xivk** [comment]
This is default behaviour, the idea is that you use another using disposing the filestream.

Most .NET API's work like this so we just copied that behaviour.

If you based this code on the samples, let me know, I'll fix it.

**Comment by hmanning** [comment]
Hi mate,

Yeah I went off this sample at the bottom:
https://github.com/OsmSharp/core

Fixed it using another ( using ) as so:
```
                using (var PBFStream = new PBFOsmStreamSource(new FileInfo(@"D:\Work\MapRedraw_V6\PBF\" + GlobalMembers.SelectedPBF).OpenRead()))
                {
                    var PBFStreamBoundingArea = PBFStream.FilterBox((float)LongLeft, (float)LatTop, (float)LongRight, (float)LatBot);
                    using (var fileStream = File.Create(@"D:\Work\MapRedraw_V6\FilteredPBF\test.osm.pbf"))
                    {
                        var target = new PBFOsmStreamTarget(fileStream);
                        target.RegisterSource(PBFStreamBoundingArea);
                        target.Pull();
                    }
                }	
```
Kind regards.

**Comment by xivk** [comment]
Ok keeping this open until sample is fixed, on my phone now...

Thanks for reporting the issue!
