### ISSUE TITLE
Cant find ShapefileDataWriter

### ISSUE THREAD

**Issue by mathisloge** [OsmSharp/core#36]
Hey there!

In the Samples is the ShapefileDataWriter, but i cant find it. Is it in some other NuGet-Package?

**Comment by xivk** [comment]
Yes, you need to install NetTopologySuite, it should be there when you run the sample:

https://github.com/OsmSharp/core/blob/develop/samples/Sample.GeometryStream.Shape/Sample.GeometryStream.Shape.csproj#L21 => that's the most important package.

**Comment by mathisloge** [comment]
Oh, I overlooked that. Thank you!
