### ISSUE TITLE
Exsample project don't build in visual studio 2015

### ISSUE THREAD

**Issue by testniracun** [OsmSharp/core#37]
I have downloaded zip from github site and unzipped it. Then I double click on OsmSharp.sln and my VS2015 says "One or more projects in the solution were not loaded correctly. Please see the Output Window for details."

We were unable to automatically populate your Visual Studio Team Services accounts.
The following error was encountered: TF400813: Resource not available for anonymous access. Client authentication required.

How to fix this?

**Comment by xivk** [comment]
Building OsmSharp is only supported either using:

- VS 2017
- VS Code and .NET Core
- Other methods supporting the new csproj format.

You can use OsmSharp in VS 2105 too but you need to create a new project from scratch. To use the samples for example, create a new project and add the packages you see in the sample. Then just copy/paste over the code.

For this sample in VS 2015: https://github.com/OsmSharp/core/tree/develop/samples/Sample.Filter

- Create a new empty .NET Framework project.
- Install OsmSharp nuget package.
- Copy/paste this code in Program.cs: https://github.com/OsmSharp/core/blob/develop/samples/Sample.Filter/Program.cs
- Optionally also copy over Download.cs (you can also manually download the file): https://github.com/OsmSharp/core/tree/develop/samples/Sample.Filter/Download
