### ISSUE TITLE
Support osc file with multiple create/modify/delete tags

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#41]
I'm not sure this if this is already supported or not, but it would be great if this library would be able to support updating of a database using .osc files.

**Comment by HarelM** [comment]
Any updates on this?

**Comment by HarelM** [comment]
Seems like this library supports osmchange xml reading, but when using a file generated by osmupdate that has multiple create/modify/delete tags it reads only the last one.
Here's an example: [israel-and-palestine-updates.osc.txt](https://github.com/OsmSharp/core/files/1545053/israel-and-palestine-updates.osc.txt)
I'll update the code and send a pull request.

**Comment by HarelM** [comment]
@xivk I would be happy if you could merge this and create a new NuGet package.

**Comment by HarelM** [comment]
I confused my self - the original issue was a question if osmupdate/osmconvert can be replaced by this library so it will run in-memory instead of in a different process.

**Comment by xivk** [comment]
This is now available in the latest prerelease packages.

You should be able to replace whatever osmupdate/osmconvert is doing. The only thing OsmSharp isn't very good at at the moment is writing OSM-PBF. It doesn't compress the files, like in the default format.

**Comment by HarelM** [comment]
Thanks!
Will you be able to post some code to show how it's done? Meaning how do I take the changes from `OsmChange` and update the target stream or source or what-not...
Also the OsmUpdate downloads a lot of files and merges them in order to be able to update pbf file, I'm guessing this library doesn't have this code built in, right?
