### ISSUE TITLE
Add functionality to compress changesets.

### ISSUE THREAD

**Issue by xivk** [OsmSharp/core#43]
Add functionality to compress multiple changesets into one.

**Comment by HarelM** [comment]
I'm guessing that this is the purpose of this issue but I'll ask any way.
I tried to use OsmSharp instead of osm convert to add changeset and the file size jumped from ~60 Mb to around 300Mb.
Is this what this issue should be covering?
If so, can I help in anyway?

**Comment by xivk** [comment]
No, this is about compressing changesets, multiple changesets can be converted into one that has the same effect.

**Comment by xivk** [comment]
This issue: https://github.com/OsmSharp/core/issues/46
