### ISSUE TITLE
Release OsmSharp NuGet

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#45]
I believe it's time to do an official release instead of pre-release, don't you think? :-)

**Comment by xivk** [comment]
I'll try to evaluate what I think should still be done before a new release.

If there are no more breaking changes upcoming I'll release. Sorry I need to be careful doing this.

**Comment by xivk** [comment]
Just FYI, this is what's left before the v6 release:

https://github.com/OsmSharp/core/milestone/1

The big ones are still full PBF support and the geometry interpreter, but I may leave the second one for a later date.

**Comment by xivk** [comment]
Decided to release already, the other changes aren't breaking so they can go in v6.1.
