### ISSUE TITLE
HTTP client for OSM API

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#47]
I'm using the following class as an OSM HTTP client.
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.DataAccess/OpenStreetMap/OsmGateway.cs
It uses OAuth for authentication and basically does most of what I need against OSM database.
I'm guessing other can find this useful, let me know if this is something that you think should be in this library.
I can refactor it a bit if needed.

**Comment by xivk** [comment]
Perhaps we could publish a seperate package for this? 

I'm a bit reluctant to include this here because coding directly against the OSM-API is a bit controversial and can go wrong very quickly.

**Comment by HarelM** [comment]
Not sure what you mean by "controversial" and "go wrong" but I don't mind placing it in a separate package, the only drawbacks in my perspective are:
1. The fact that this is only one class...
2. It costed me quite a lot of time to make it work right so I though it would be beneficial for others, so the less packages a developer would need in order to make it work is somewhat of a consideration, IMO.

Your call anyway, I have this code in my repo...

**Comment by xivk** [comment]
Well directly programming against the OSM-API to do automated edits is dangerous:

https://wiki.openstreetmap.org/wiki/Automated_edits

**Comment by HarelM** [comment]
I'm building a UI that facilitates OSM editing that is specific for my user needs, I can hardly call it automated. having said that, I don't think there's anything wrong with some automation on OSM data much like the bots that run on wikipedia.
Also a significant part of this client is Data fetching which is for reading and not writing.

**Comment by xivk** [comment]
If you still want some of this integrated here, I'm open to this now. It makes sense to have this here.

**Comment by HarelM** [comment]
The class that is linked above (osmgayeway) is what I had in mind.
It's battlefield tested and pretty straight forward.
You have my full consent to copy any part of it.
It needs some changes in order to leave its current place, but not a lot...
Let me know how I can assist.

**Comment by xivk** [comment]
Are you open do to do a pull-request? I would add this to the namespace `OsmSharp.API` or 'OsmSharp.IO.API' is perhaps even better. Not sure about the name 'gateway'.

**Comment by HarelM** [comment]
Sure, just guide me a little better what you want.
Logger for example, exceptions, factory? Stuff like that..

**Comment by blackboxlogic** [comment]
Since this has sat for a year, I'd volunteer to try to integrate the class into this project. I would probably try to:
- Name it OsmSharp.IO.API.Client
- Bring in some of the supporting classes
- Add functional tests
Thoughts?

If you haven't heard from me in a week, I've given up.

**Comment by HarelM** [comment]
Sounds about right, Feel free :-)

**Comment by blackboxlogic** [comment]
So... OsmSharp currently compiles into _.NETStandard1.3_, _.NETStandard2.0_ and _.NETFramework4.5_
OsmGateway.cs has a reference to [OAuth.DotNetCore](https://github.com/rhargreaves/oauth-dotnetcore) which definitely doesn't support _.NETStandard1.3_
Options:
- OsmSharp stops supporting _.NETStandard1.3_
- Api _Update_ functionality gets surrounded by compiler directives and is only available in standard2.0 and framework 4.5 (read-only operations don't require any auth)
- I try and find an OAuth library that supports all 3 configurations
- I don't implement OAuth at all, because the OsmApi [also supports basic auth](https://wiki.openstreetmap.org/wiki/API_v0.6#URL_.2B_authentication)
- Something else I haven't thought of?

**Comment by HarelM** [comment]
My 2 cents: 
I think that requesting the user to send you the OSM user name and password is a security breach - I believe this is what OAuth is for.
I think 3 is hard - the existing package is the most commonly used package I found that also worked at that time, but it might be possible to find another one.
I like options 1 and 2 better...

**Comment by xivk** [comment]
Hey, thanks for your efforts but I don't think adding a full client to OsmSharp is the way to go. I don't mind support for parsing responses for the OSM-API but adding a full client including OAuth is a step too far.

It would also mean an extra dependency, and that's a definite no. I see this type of functionality coming together:

- OsmSharp purely for parsing/serialization the data (that's it's only purpose).
- Another library for authentication (OAuth, basic, whatever in the future...).

These two need to come together in applications built using OsmSharp not in OsmSharp itself. If you want a package with a read-to-go client for the OSM-API it needs to be seperate from OsmSharp, sorry about that.

**Comment by blackboxlogic** [comment]
@xivk I appreciate guidance.

Could the separate package live near OsmSharp/Core, maybe in a project like OsmSharp/ApiClient? I wonder if anyone would ever find or trust blackboxlogic/OsmApliClient

Should the client project attempt to support .NETStandard1.3, .NETStandard2.0 and .NETFramework4.5, to be fully compatible with OsmSharp/Core?

**Comment by xivk** [comment]
Send us a message via the contact form here to get in touch directly:

http://www.itinero.tech/

We can host the package under the OsmSharp organization, use our build pipeline and everything but you will need to maintain it. 

I would just use netstandard2.0 and nothing else. Still using .NET framework 4.5 is not a good idea and the latest .NET framework versions support netstandard2.0 as do all recent .NET core versions so it's perfect.

**Comment by HarelM** [comment]
@xivk @blackboxlogic  I'll be happy to help maintain it.

**Comment by blackboxlogic** [comment]
@HarelM I've sent an initial message through their contact form. I welcome collaborators. Lets move this to chat? I made an #osmapiclient channel in OpenStreetMap's slack workspace.

**Comment by HarelM** [comment]
The following project is currently where the Client API code will be, it might move to OSMSharp organization when it matures I believe.
https://github.com/blackboxlogic/OsmApiClient/
This issue can probably be closed...

**Comment by HarelM** [comment]
API is fully operational and a first production release was published to NuGet. Closing.
