### ISSUE TITLE
Issues with released version 6.0?

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#49]
I'm seeing a very strange behavior - I'm migrating my project from .net core 1.1 to 2.0.
Since I'm upgrading infra I though I should move out of the prereleased versions to 6.0.
When I did that the following code stopped working as expected:
```
var source = new PBFOsmStreamSource(osmFileStream);
                var completeSource = new OsmSimpleCompleteStreamSource(source);
                var namesDictionary = completeSource
                    .Where(o => string.IsNullOrWhiteSpace(o.Tags.GetName()) == false)
                    .GroupBy(o => o.Tags.GetName())
                    .ToDictionary(g => g.Key, g => g.ToList());
```
It started to return an empty dictionary and it seems like it doesn't scan the pbf file (`osmFileStream` is a stream to a pbf file).
Are you aware of this issue?
I have reverted back to pre08 and it started working again...

**Comment by xivk** [comment]
That should work as you have it there... will check this.

**Comment by HarelM** [comment]
Any updates one this?

**Comment by xivk** [comment]
Sorry very very busy at moment, could be another few weeks before I get to checking this.

**Comment by HarelM** [comment]
Sure, no problem, but if this is the case I would consider either removing this version or marking it as pre-release...

**Comment by xivk** [comment]
It's not possible to remove but I unlisted it for now.

**Comment by xivk** [comment]
I confirmed this is working as it should.

**Comment by HarelM** [comment]
@xivk it seems this issue exists in latest version as well. not sure what to do, any idea?
![image](https://user-images.githubusercontent.com/3269297/40937341-01354cc0-6847-11e8-8ccd-3b8fee2d7cac.png)

**Comment by xivk** [comment]
You are 100% sure that this is not working? I tested the same code it was working fine. Can you build a sample project reproducing this, including data, and send it to me?

**Comment by HarelM** [comment]
It seems that the stream was not at the starting position and due to that it didn't work properly.
Has this behavior changed lately?
When seeking to the begging it seems to start working again.
My bad I guess...

**Comment by xivk** [comment]
Not sure this has changed but it's possible. It's a bit unclear now how OsmSharp handles the source streams, does it need to seek to the beginning or not when resetting. At least it should be consistently the same behavior everywhere but I'm not sure of that either.

There was a commit to handle non-seekable streams recently, perhaps it has something to with that.

**Comment by HarelM** [comment]
The following seems to solve this - seek to begin.
Your call whether to close this or not, I'll add seek to begin before every read of the OSM stream just to make sure this works properly.
![image](https://user-images.githubusercontent.com/3269297/40938199-d48f2508-6849-11e8-9d0d-3d00107ccf81.png)
Thanks a lot for the quick response!
