### ISSUE TITLE
Documentation is extremely partial

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#5]
Hi, 

I'm trying to build a Nominatim-Photon like search engine for my project.
I'm very much interested in this project as I see the potential in it and will also be happy to help out if needed.
Unfortunately I'm unable to understand how to operate all this - the documentation is very partial
What's I'm currently trying to achieve is the following:
1. read an pbf file.
2. iterate through all the nodes ways and relations and index them into an elastic search database.
3. Add a controller to my WebApi in order to facilitate the search.

The project [Israel Hiking](http://www.github.com/israelhikingmap/site) is open source and runs on IIS on a windows server.

**Comment by xivk** [comment]
@HarelM I updated the [wiki](https://github.com/OsmSharp/core/wiki) with some docs and create samples for most of the functionality. Considering this issue closed for now unless you can see other important usecases I haven't covered yet.

**Comment by HarelM** [comment]
Thanks for the update, keep up the good work.
Adding a reference to the wiki in the readme.md file would also let people know that the wiki is active and helpful.
Since you added the Geo package I would advise to write about it some where.
Since you are creating a framework for OSM it might be helpful to make an examples page/files to demonstrate the power of this awesome framework, with small examples of how to do things "the right way".
Kudos.
