### ISSUE TITLE
Incompatibility with geofabrik extracts, as of may 03 '18

### ISSUE THREAD

**Issue by iPhyse** [OsmSharp/core#57]
It looks like geofabrik.de has implemented the new EU Law - General Data Protection Regulation (GDPR).
ref: https://en.wikipedia.org/wiki/General_Data_Protection_Regulation

Announcement on geofabrik:

> _The OpenStreetMap data files provided on this server do not contain the user names, user IDs and changeset IDs of the OSM objects. These metadata fields contain personal information about the OpenStreetMap contributors and are subject to data protection regulations in the European Union. Please note that these regulations apply even to processing that happens outside the European Union because some OpenStreetMap contributors live in the European Union._ 

The issue occurs when data is tried to be extracted to a list:
```csharp
var source = new PBFOsmStreamSource(fileStream);
var filteredQuery = from osmGeo in source where
                         osmGeo.Type == OsmGeoType.Way &&
                         osmGeo.Tags.ContainsKey("highway") &&
                         !osmGeo.Tags.Contains("highway", "cycleway") &&
                         !osmGeo.Tags.Contains("highway", "bus_stop") &&
                         !osmGeo.Tags.Contains("highway", "street_lamp") &&
                         !osmGeo.Tags.Contains("highway", "path") &&
                         !osmGeo.Tags.Contains("highway", "turning_cycle") &&
                         !osmGeo.Tags.Contains("highway", "traffic_signals") &&
                         !osmGeo.Tags.Contains("highway", "stops") &&
                         !osmGeo.Tags.Contains("highway", "pedestrian") &&
                         !osmGeo.Tags.Contains("highway", "footway") || 
                         osmGeo.Type == OsmGeoType.Node
                    select osmGeo;

var collectionComplete = filteredQuery.ToComplete();
var ways = collectionComplete.Where(x => x.Type == OsmGeoType.Way).ToList(); //<-- Error occurs with the new *-latest.osm.obf files as of May 3rd. 
```
previous -osm.pbf files, containing the user names, user IDs and changeset IDs of the OSM objects, are processed without any errors.

**Comment by xivk** [comment]
I can't reproduce this issue. I added a test like this to the functional test project and tried with one of geofabrik's files and things seem fine.

Can you try with the latest OsmSharp? Did you use v5.0.6? OsmSharp is very close to releasing 6.0. Feel free to send me the file and reopen if this is still an issue.
