### ISSUE TITLE
GeoJson Feature object throws exception when try to serialize it to json string

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/core#6]
I'm trying to convent an OsmComplete object to geojson ``` OsmSharp.GeoFeatures.Feature```.
I have a working code that does the conversion, but when I want to serialize it I'm getting an exception:
``` The method or operation is not implemented. ```
I'm using newton json:
```
JsonConvert.SerializeObject(geojson)
```
I've been using [GeoJson.Net](https://www.nuget.org/packages/GeoJSON.Net) which I find follows all the geojson guidelines. I suggest to use it in this project as well. :-)

**Comment by xivk** [comment]
I suggest you use NTS: https://github.com/NetTopologySuite/NetTopologySuite and with the GeoJSON io package. There is also OsmSharp.Geo (no package yet) where you can have a look at the convert OSM data to features/geometries.

**Comment by xivk** [comment]
OsmSharp.Geo is here: https://github.com/OsmSharp/core/tree/develop/OsmSharp.Geo

**Comment by HarelM** [comment]
So this means I can remove the entire conversion code I wrote?
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Converters/OsmGeoJsonConverter.cs
When are you planning on releasing this code?

**Comment by xivk** [comment]
Not sure if your code is identical but the idea is the same I think... I'll try and see if I can create a package for OsmSharp.Geo in the next couple of days...

**Comment by HarelM** [comment]
I looked at the code in OsmSharp.Geo.DefaultFeatureInterpreter.cs and it looks like it uses the tags to learn about the geometry.
Since OSM can be edited by anyone, using tags is weak, IMO.
I have tested my code with a vast variety of features in Israel and I can say with 95% confidence that it does a correct job, you are free to use it if you'd like.
Do OsmSharp relies on NTS for GeoJson object?
If you think that migration my code to NTS will help you I don't mind doing it, GeoJson.Net was the first google .Net package I found and it proved to simple and elegant since all I needed was GoJson POCO classes.

**Comment by xivk** [comment]
Some features are impossible to convert without using the tags, for example borders, large landuse bodies, multipolygons in general and pedestrian areas. And these are just some examples. Not sure what you need exactly but you really need to use the tags in many cases...

Only OsmSharp.Geo relies on NTS for geometries and IO (for example to/from GeoJSON).

**Comment by HarelM** [comment]
Thanks for the tip (love the fallout avatar :-)), I'll give it a go once you publish the package.
I looked into NTS and it also has a dependency on GeoAPI, all and all seems like the library is a bit of an overkill for the mere task of holding in memory GeoJSON object and serializing it to file/web service response, but I'm kinda new to the GIS world in term of .Net so I might not know the trade's secrets :-).
The reason I use your library (which is great BTW) is for the creation of a nominatim-like server that harness the power of elastic search (which work great!:-)).
So the only objects I need to convert from OSM to GeoJson are those with names, and I group them by name before trying to convert them (much like the nominatim logic), so it might be that my code is simpler than it should be...
Give me a ping when you publish the Geo Package.

**Comment by xivk** [comment]
I know, NTS seems overkill for a lot of apps but it enables a lot of features and it's the only decent library that can handle a lot of file formats and is 'OGC compliant'. When not using it, it would mean implement all of this IO/Geo functionality again in OsmSharp, that would be even more overkill :-)

**Comment by xivk** [comment]
There is now an OsmSharp.Geo package, published alongside OsmSharp.Core:

**Comment by HarelM** [comment]
Sorry, I tried, but this library is not compatible with web API out of the box.
When returning a FeatureCollection from ApiController I'm getting the below invalid object... :-(
There's probably an easy way to solve this but I rather not change my entire server side code to something that I feel is lesser than what I'm currently using.
I'll keep my geojson-osm conversion code hoping it will be enough for my needs.
Thanks anyway :-)
```json
{"<Features>k__BackingField":[{"_geometry":{"_coordinates":{"Coordinates":[{"X":32.0,"Y":33.0,"Z":"NaN"}],"_dimension":3},"_factory":{"_precisionModel":{"_modelType":0,"_scale":0.0},"_coordinateSequenceFactory":{},"_srid":0},"_userData":null,"_envelope":null,"_srid":0,"_dimension":0,"<Boundary>k__BackingField":null,"<BoundaryDimension>k__BackingField":0},"_attributes":{"_attributes":{}}}],"<Type>k__BackingField":"FeatureCollection","<CRS>k__BackingField":null}
```

**Comment by HarelM** [comment]
Sorry for nagging, in case you want, here are the tests I wrote to make sure my converter is working as expected, it covers most of the scenarios I could think of:
https://github.com/IsraelHikingMap/Site/blob/master/Tests/IsraelHiking.API.Tests/Converters/OsmGeoJsonConverterTests.cs
