### ISSUE TITLE
Convert source stream to complete stream

### ISSUE THREAD

**Issue by wspom2k5** [OsmSharp/core#62]
If I want convert source filtered by tag value to complete stream I need also get all node/way/relation for for the creation of complete object (as in https://github.com/OsmSharp/core/tree/master/samples/Sample.CompleteStream)? Is there another solution for large data sets?

**Comment by xivk** [comment]
Can you describe your issue in more detail? 

If you have a really large dataset and want to filter objects I would recommend working in two passes:

1. Filter all objects you need and keep the id's or their children (node id's for ways and members for relations).
2. Do a second pass and this time convert the objects to complete objects but keep on the objects you have from the first pass.

Feel free to reopen if this doesn't answer your question.

**Comment by wspom2k5** [comment]
Members of relations maybe a ways. So then we need next pass to get node id's for nested ways? To build completed object we need get all nested object recursively?

**Comment by xivk** [comment]
The only way to do that is to either keep *all* the nodes or to do three passes over the data. First get relation members, then way node id's for member ways and then the actual nodes. Depending on the size of your dataset you can decide what option to take.
