### ISSUE TITLE
How to properly retrieve information from differential updates

### ISSUE THREAD

**Issue by goncalo-oliveira** [OsmSharp/core#70]
Hi,

I've successfuly used `PBFOsmStreamSource` to retrieve filtered data to build a custom database. But now, I wanted to be able to update that with differential updates. These differential updates have a different format, they're basically XML files with *modify or delete* (or insert? haven't seen one) instructions. I started out by using the `XmlOsmStreamSource` and I am able to apply the filters the same way that I did with the PDF, but I can't seem to figure out if the node or way is to be deleted or modified or whatever.

Here's a simplified excerpt of how I'm processing the stream.

```
                var source = new XmlOsmStreamSource( fileStream );

                var filtered = from element in source
                               where element.Type == OsmSharp.OsmGeoType.Node ||
                                (element.Type == OsmSharp.OsmGeoType.Way && (element.Tags?.Any( x => x.Key.Equals( "highway" ) && x.Value.Equals( "bus_stop" ) ) == true))
                               select element;

                var complete = filtered.ToComplete();

                foreach ( var element in complete )
                {
                    // ...do stuff
                }
```

Can anyone point me in the right direction?

Cheers!

**Comment by xivk** [comment]
There are already some things in OsmSharp that can help you:

https://github.com/OsmSharp/core/tree/master/src/OsmSharp/Changesets

There is also an implementation of an in-memory database that has an `ApplyChangeset` method, that should get you started:

https://github.com/OsmSharp/core/blob/master/test/OsmSharp.Test/Db/HistoryDbTests.cs#L80
https://github.com/OsmSharp/core/blob/master/src/OsmSharp/Db/HistoryDb.cs#L192

**Comment by goncalo-oliveira** [comment]
Hi @xivk,

Thanks for you reply.

I already came across change sets structure and did go through some of the tests including it, but I'm still missing how I can relate it from the changes .osc file.

**Comment by goncalo-oliveira** [comment]
Ahh of course! Thank you @xivk. I was looking for a way to do that with `XmlOsmStreamSource` and that didn't work. But deserializing it manually as an `OsmChange` works perfectly. Was just looking at the wrong place I guess.

Cheers!
