### ISSUE TITLE
How to read data?

### ISSUE THREAD

**Issue by BruceKristelijn** [OsmSharp/core#71]
Hi!, I am trying to read data with my application.

`        using (FileStream fileStream = File.OpenRead("test.osm.pbf"))
        {

            // create source stream.
            var source = new PBFOsmStreamSource(fileStream);

            foreach (var element in source)
            {
                Debug.Log(element.Type);
            }
        }`

This is my code but the output is:

`ProtoException: Invalid field in source data: 0`

Is there a possibility my pdf files are wrong?

**Comment by xivk** [comment]
I don't think this is broken. This is tested at every build. If you are sure your PBF file is a proper one send it and we test what's happening.
