### ISSUE TITLE
PBFReader reads wrong versions

### ISSUE THREAD

**Issue by Shkarface** [OsmSharp/core#79]
I have made a project to import osm data into mongodb, all is working correct except for the PBFReader versions, all the element versions are read wrong in increasing value {2 , 5 , 10 , 25 .. n } , this doesn't happen with XMLReader.

PBFReader:
![Screenshot from 2019-08-01 09-48-26](https://user-images.githubusercontent.com/1114849/62271594-b1c71900-b441-11e9-99f7-c33b1dc90d6f.png)

XMLReader:
![Screenshot from 2019-08-01 09-48-45](https://user-images.githubusercontent.com/1114849/62271625-c9060680-b441-11e9-9b20-674807554d1f.png)

**Comment by Shkarface** [comment]
@xivk  Is there any news on this issue? currently all our files need to be converted to XML OSM then read by OsmSharp because of this issue and it increases build times drastically!

**Comment by blackboxlogic** [comment]
Could you attach a sample (small) .pbf file? I could take a look.

**Comment by xivk** [comment]
I think this happens on any for the osm.pbf files, there are some in the test project:

https://github.com/OsmSharp/core/tree/develop/test/OsmSharp.Test/data/pbf

**Comment by Shkarface** [comment]
This happens on all .pbf files

**Comment by blackboxlogic** [comment]
I've never used a pbf, but sure looks like this is the problem?
https://github.com/OsmSharp/core/blob/d17dc0168cbb65d1d15389ee7026434256046be7/src/OsmSharp/IO/PBF/Encoder.cs#L89-L90
should be
` currentVersion = primitivegroup.dense.denseinfo.version[idx];`
I went hunting for a spec and found
https://wiki.openstreetmap.org/wiki/PBF_Format#Nodes
`repeated int32 version = 1 [packed = true];` which _doesn't have_ `// DELTA coded` after it, which supports my suggestion for a change.

Do you have any reason to believe my suggesion isn't the correct solution?

**Comment by xivk** [comment]
Awesome @blackboxlogic 

You looked at this with a fresh pair of eyes. I assumed the bug was more complex because I couldn't image this being there from the beginning.

Thanks again! :+1:

**Comment by blackboxlogic** [comment]
@xivk Any guess when this might be released as 7.0.0 or 7.0.0-pre006? I noticed the build is paused.

**Comment by xivk** [comment]
This build move to another server. I'll see if I can give you access there. I'm also considering maybe doing the builds via github actions.

Anyway, with this fix we are close to a release. I'll see when I can make a stable but the last package should be there on nuget.

**Comment by blackboxlogic** [comment]
No need to give me access to build server. I'll ask if/when I think I need it. Thanks.
