### ISSUE TITLE
Doesn't generate Polygons like ogr2ogr etc

### ISSUE THREAD

**Issue by matthewsheeran** [OsmSharp/core#85]
But only Points and Lines albeit some of them closed I think.
I am using the ToJson() (NetTopolgysuite/Newtonsoft) from Sample.GeometryStream though it looks like the input Features reflect this output too.
I guess I will have to experiment, try a triple pass Nodes, Ways, Relations maybe Shapefile as well then load up the OsmSharp+OsmSharp.Geo (master branch) source code projects step through debug and breakpoint it..
I was very pleased to see DefaultFeatureInterpreter handle areas (master branch) and try to make LinearRings hence Polygons and on the basis of tags per https://wiki.openstreetmap.org/wiki/Overpass_turbo/Polygon_Features so this stuff should be working methinks..

Saving me a ton of effort which I will be exceedingly grateful for but otherwise I will reconsider NuGet GDAL-OGR plus my own ports of ogrinfo+ogr2ogr to C# instead (untested but my OSM to SQLite test worked flawlessly) just to get something going though I want to avoid the bloat plus the user complexity of osmconf.ini..

BTW: I would be happy to contribute and help too: this will be a very nice project if and when it truly works for me: PBFReader reads wrong versions #79 opened on Aug 1 by Shkarface has me worried as I need PBF support as well (and who doesn't because of the size and extraction overheads of OSM XML).

Regards,
Matthew

**Comment by xivk** [comment]
Matthew, thanks for your message.

#79 is indeed the most urgent, I've looked at it already but couldn't immediately find the issue. 

The feature interpreter is very complex and it takes a lot of effort to maintain. That's also why it's only available in just a few OSM tools. The OsmSharp one won't work for all area types but if you are willing to work on it I'm sure we can improve it.

The issue with wrapping GDAL-OGR is that it doesn't port to all platforms nicely, that's what OsmSharp tries to provide.

**Comment by matthewsheeran** [comment]
Ill keep digging (now using master instead). My only other concern is memory consumption vs GDAL-OGR and at least one Python script I found which claims to be whole planet capable but I don't think it was PBF and only OSM XML which would be enormous by comparison and therefore a bit silly IMHO.
So I take it that the stream as it is streamed and processed with take up memory with the PBF/OSM file so that on a modern PC I would be limited to processing say a 4GB or 8GB PBF/OSM chunk of the planet at a time?
Did u get some or have some sample data for #79 preferably from the user then cut it down to half to a dozen of whatever OSM Elements it involves that turn up out of order..?

**Comment by xivk** [comment]
I would recommend filtering the stream getting only the features you want. If you do the filtering properly and not try to extract for example 'all the road on the planet' things should be fine.

The filtering should happen *before* the feature interpreter then it won't start working on features you don't need.

**Comment by xivk** [comment]
Oh and there are small tests files in the unittests and the issue is there for all data.

**Comment by matthewsheeran** [comment]
Thanks: yeah I'll have to start looking at and running the unit tests too which will of course give me some tips/insights into the API and how to use it..

**Comment by matthewsheeran** [comment]
Hi Ben
It is still on my radar to eventually get back to my GUI POI Extractor
Project: I am going to do it with GGDAL-OGR and osm tools as well as your
OSM as two methods/providers in my project.

Will be useful then to compare the two: eventually..

There is no simple GUI out there open source or commercial for non-expert
non command-line GIS people and companies charge a lot for this data: try
AUD$40,000 for annual Australia-wide POIs last time I heard! ;-)

So this app of mine will be a winner as far as i am concerned. And if I
need your help with your sources I can kick back some cash your way: when I
get there and it takes off, I have other small GUI apps in mind in this
space like AU Geocoded National Address File processing (done) including
ESRI-compatible Geocoding Service using ServiceStack and Elasticsearch in
C# (hence my slowness as the latter is also a lot of private project work
of mine plus the company website for all this too eventually..)..

Regards
Matthew
