### ISSUE TITLE
Implement to string on OsmGeoKey

### ISSUE THREAD

**Issue by xivk** [OsmSharp/core#92]

**Comment by blackboxlogic** [comment]
Would you be content with 
`Type.ToString() + Id;`
to produce something like "Way209382"

**Comment by xivk** [comment]
This is a good place for inspiration:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/Way.cs#L48

Also, in the past I've considered have the ToString() return the osm browse URL:

https://www.openstreetmap.org/node/3956438680

If find that to be extremely convenient to have a quick link to the data you are looking at.

**Comment by blackboxlogic** [comment]
Looks like this got fixed in https://github.com/OsmSharp/core/commit/1b3df9048900dcf3cb48f379ecbba2a0860f47a8
