### ISSUE TITLE
Trouble with FeatureConversion

### ISSUE THREAD

**Issue by KeldorKatarn** [OsmSharp/core#94]
I am trying to convert a number of rivers to GeoJSON.
I already successfully extracted all European rivers from the database into a separate file to make further processing faster.
However now I'm running into issues.

`            var source = new PBFOsmStreamSource(inputFileStream);

            var filtered = source.Where(el => el.Type != OsmGeoType.Relation ||
                                              el.Tags.Contains("name", "Elbe")).ToArray();

            var complete = filtered.ToComplete().ToArray();
`

This code results in a compelte list of only Nodes. No Ways, no Relation. Why does the ToComplete() only create Nodes? It seem to fail to create CompeleteWay and CompleteRelation objects?

Also..  why can't ToFeatureSource() be called on a list of complete objects? How to I create a feature source from a single relation. If I filter the source down to only relations and then create the featureSource it's empty. But if I leave all the nodes and ways in, then it creates tons of points.

Somehow I'm missing something here?

I'd be greatful for any help.

**Comment by xivk** [comment]
Extracting these types of big polygon features from OSM data is non-trivial. It's not uncommon for this to break, I'm not even sure I've ever tried this with OsmSharp before. 

I can tell you what ToComplete() does: it creates Ways with all the nodes instantiated and relations with all it's members instantiated. So no id references but the actual node/member objects. However it only returns complete objects (Nodes, CompleteWays and CompleteRelations) when **all** members/nodes can be found. Nodes are always considered 'complete', a way only when all nodes are in the source stream and a relation only when all of it's members can be found. 

It could be a great addition to OsmSharp to optionally have ToComplete() also return CompleteWays or CompleteRelations with members instantiated but also if it can't find all of them.

**Comment by KeldorKatarn** [comment]
I am actually just extracting the center lines... but I guess it's possible I've filtered a way a couple of nodes if those weren't tagged as part of a waterway...

I guess what I could do is operate on the entire dataset, keep the nodes, then turn it into a complete set and then filter out the relations and create the simple versions again and only store those nodes and ways which were members of a river relation... but I guess that would mean I have to keep ALL nodes in memory?

**Comment by xivk** [comment]
I recommend looking at the powerline sample, filtering is done there in 2
passes if I'm remembering correctly. That could be a solution in your case.

**Comment by KeldorKatarn** [comment]
That sample is not really 100% clear to me. Extracting the rivers should work by leaving all nodes and ways in the enumerable and filtering relations for the rivers

`            var source = new PBFOsmStreamSource(inputFileStream);

            var filtered = source.Where(el => el.Type != OsmGeoType.Relation || el.Tags.Contains("waterway", "river"));

            // filter out only linestrings.
            var features = filtered.ToFeatureSource().Where(f => f.Geometry is MultiLineString).ToArray();
`

This however gives me an empty features collection. Relations should be turned into MultiLineStrings... at least that's what overpass-turbo is doing. But this is empty.
I mean if I get all the individual parts of a river as LineStrings, then what use is filtering for relations? Those are supposed to collect all those ways and pack them into one.
The geometry export should do the same? Or am I missing something here. Does OsmSharp.Geo turn relations into some other geometry type?

**Comment by xivk** [comment]
The geometry interpeter probably doesn't implement multilinestring-relation
support.

I can't look at this now in detail, on my phone only today sorry.

**Comment by KeldorKatarn** [comment]
Unfortunately the library seems to be unusable for me. I cannot manage to extract relations and turn them into the data I need. Off to search again or do things manually.
