### ISSUE TITLE
inconsistent code in encoding Longitude in densenode ?

### ISSUE THREAD

**Issue by EddyToo** [OsmSharp/core#98]
When trying to learn the pbf format and library I ran into the following section in PBFOsmStreamSource.cs (lines 290-293)

```
            var currentLat = Encoder.EncodeLatLon(current.Latitude.Value, block.lat_offset, block.granularity);
            var currentLon = Encoder.EncodeLatLon(current.Longitude.Value, block.lat_offset, block.granularity);
            var previousLat = Encoder.EncodeLatLon(previous.Latitude.Value, block.lat_offset, block.granularity);
            var previousLon = Encoder.EncodeLatLon(previous.Longitude.Value, block.lat_offset, block.granularity);
            groupDense.lat.Add(currentLat - previousLat);
            groupDense.lon.Add(currentLon - previousLon);

```
This looks like a copy/paste/edit error. The previous and current Longitude should logically be offset against block.lon_offset. Given the last line where only the diff is used between currentLon and previousLon is stored in the block this will most likely not create an actual bug but there might be some odd edge case?

**Comment by xivk** [comment]
Yep, this is probably a bug, I guess you refer to these lines:

https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/IO/PBF/Encoder.cs#L289

If you can create a test and then I'll see if I can fix this.

**Comment by EddyToo** [comment]
Yes Encoder.cs. my bad.

And I don't think it easily creates wrong output (if ever)

Suppose: (ignoring granularity) 
```
block.lat_offset = 10
block.lon_offset = 50
currentLongitude.Value = 25
previousLongitude.Value = 40

```
Then current code:
```
currentLon = 25 - 10 = 15
previousLon = 40 - 10 = 30
groupDense.lon.Add( 15-30 = -15 )

```
Should logically be:
```
currentLon = 25 - 50 = -25
previousLon = 40 - 50 = -10
groupDense.lon.Add( -25--10 = -15 )

```
Identical results

**Comment by pietervdvn** [comment]
I have doublechecked the math. `EncodeLatLon(value, offset, granularity)` actually boils down to `(value * 100000000 - offset) / granularity`. 

The calculate difference `currentLon - previousLon` is thus, if we expand it (with the old 'incorrect' code):

```
currentLon - previousLon
= EncodeLatLon(current.Longitude, block.lat_offset, block.granularity) - EncodeLatLon(previous.Longitude, block.lat_offset, block.granularity)

[Expanding the definition]
= ((current.Longitude * 100000000 - latOffset)/ granularity) - ((previous.Longitude * 100000000 - latOffset)/ granularity) 

[Splitting of the fraction 'granularity']
= (current.longitude * 100000000 - latOffset - (previous.Longitude * 100000000 - latOffset)) / granularity

[If we remove the parenthes, we get]
= (current.longitude * 1000000 - latOffset - previous.Longitude * 10000000 + (PLUS!) latOffset) / granularity

[We can remove the latOffset here as they cancel each other out]
= (current.longitude - previous.Longitude) * 1000000 / granularity.
```

This indeed proves that the offset will always disappear in this case (except maybe in the case that some value will overflow). In any case, it should not have behaved buggy, but I've changed it to use `block.lon_offset` anyway as it is clearer.
